FROM golang:1.20.2-alpine AS go-builder

ENV GOOS=linux GOARCH=amd64 CGO_ENABLED=0 appname=personal-website-golang
WORKDIR /$appname

COPY ../.. .

RUN apk add git &&\
    apk add ca-certificates

RUN go build -o web /app/cmd/web/

FROM scratch

ENV appname=personal-website-golang
WORKDIR /$appname

COPY --from=go-builder /$appname/web .
COPY --from=go-builder /$appname/conf.d conf.d
COPY --from=go-builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/ca-certificates.crt
ADD https://github.com/golang/go/raw/master/lib/time/zoneinfo.zip /zoneinfo.zip
ENV ZONEINFO /zoneinfo.zip

ENTRYPOINT ["./web"]