FROM golang:1.19-alpine AS go-builder

ENV GOOS=linux GOARCH=amd64 CGO_ENABLED=0
WORKDIR /app

RUN apk add git &&\
    apk add ca-certificates \

RUN go build -o admin /app/cmd/admin/

FROM scratch

ENV appname=personal-website-golang
WORKDIR /$appname

COPY --from=go-builder /$appname/$appname .
COPY --from=go-builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/ca-certificates.crt
ADD https://github.com/golang/go/raw/master/lib/time/zoneinfo.zip /zoneinfo.zip
ENV ZONEINFO /zoneinfo.zip

ENTRYPOINT ["./sbk-match-info"]