# docker-compose.yaml
version: "3"
services:
  admin:
    container_name: personal-website-golang-admin
    build: ./admin
    tty: true
    volumes:
      - ./:/personal-website-golang
    network_mode: host