# docker-compose.yaml
version: "3"
services:
  admin:
    container_name: personal-website-golang-admin
    build:
      context: ../..
      dockerfile: ./sandbox/docker-compose/admin/dockerfile
    tty: true
#    volumes:
#      - ./:/personal-website-golang
    network_mode: host